# Used for macOS
name: raopt
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - hdf5=1.10.6
  - matplotlib=3.5.1
  - pandas=1.4.2
  - pip=21.2.4
  - python=3.8.13
  - scikit-learn=1.0.2
  - shapely=1.7.1
  - tqdm=4.64.0
  - pip:
    - h5py==3.11.0
    - haversine==2.5.1
    - keras-preprocessing==1.1.2
    - numpy==1.24.3
    - protobuf==3.20.3
    - scipy~=1.10.1
    - tensorboard==2.13.0
    - tensorflow==2.13.0
    - utm==0.7.0
